---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/posts.json":
    parameters:
    - name: include
      in: query
      required: false
      description: Include related resources, e.g. `include=author` or `include=author,channel`
      schema:
        type: string
    - name: page
      in: query
      required: false
      description: 'Show a specific page (default: 1)'
      schema:
        type: string
    - name: per
      in: query
      required: false
      description: Show more or less than 10 posts
      schema:
        type: string
    get:
      summary: list posts
      responses:
        '200':
          description: successful
  "/posts/{slug}.json":
    parameters:
    - name: slug
      in: path
      description: E.g. `5099-i-don-t-know`
      required: true
      schema:
        type: string
    - name: include
      in: query
      required: false
      description: Include related resources, e.g. `include=author` or `include=author,channel`
      schema:
        type: string
    get:
      summary: show post
      responses:
        '200':
          description: successful
        '404':
          description: not found
  "/posts/random.json":
    get:
      summary: show a random post
      responses:
        '200':
          description: successful
  "/channels/{slug}.json":
    parameters:
    - name: slug
      in: path
      description: E.g. `ruby`
      required: true
      schema:
        type: string
    - name: include
      in: query
      required: false
      description: include related resources, e.g. `include=author` or `include=author,channel`
      schema:
        type: string
    - name: page
      in: query
      required: false
      description: 'Show a specific page (default: 1)'
      schema:
        type: string
    - name: per
      in: query
      required: false
      description: Show more or less than 10 posts
      schema:
        type: string
    get:
      summary: list posts for a given channel
      responses:
        '200':
          description: successful
        '404':
          description: not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
